name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: ramdocker22/mongodb:v1
    container_name: mongodb
  catalogue:
   build: ./catalogue
   image: ramdocker22/catalogue:v1
   container_name: catalogue
   depends_on:
   - mongodb
  frontend:
    build: ./frontend
    image: ramdocker/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
network:
  default:
    name: roboshop
    driver: bridge
    external: false